apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  # labels of deployment resource
  labels:
    app: java-app
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: java-app
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: java-app
        image: rajudonkeshwar/java1:image-version
        ports:
        - containerPort: 8080






