apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  # labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: rajudonkeshwar/java1:image-version
        ports:
        - containerPort: 80






