kind: Service
apiVersion: v1
metadata:
  name: java-app
spec:
  type: NodePort
  selector: # labels are used as selectors
    app: java-app
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 8080
    nodePort: 30009